name: FRC-2024-Vision
channels:
  - conda-forge
  - nodefaults
  - pytorch
dependencies:
  - python
  - opencv=4.8.1
  - py-opencv=4.8.1
  - ultralytics
  - ipykernel
  - pytorch
  - torchvision
  - cpuonly
  - pyrealsense2
  - dill
